# Generated by Django 4.1.3 on 2022-12-03 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translation', models.JSONField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('lastRead', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/defaultUserIcon.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='user',
            name='news',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('words', models.ManyToManyField(to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(editable=False)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='dictionary.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='results',
            field=models.ManyToManyField(to='dictionary.result'),
        ),
        migrations.AddField(
            model_name='user',
            name='wordGroups',
            field=models.ManyToManyField(to='dictionary.wordgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='words',
            field=models.ManyToManyField(to='dictionary.word'),
        ),
    ]
